### PR TITLE
check ich "ch_names" present in annotations

### LINKED ISSUE #99: no 'ch_names' in annotations -> Error
I'm using pybv (v0.7.4) via MNE (v1.1.1) to concatenate and rewrite raw BV files. 
It raises a `Key error: ch_names` and stops. It seems the culprit is [here](https://github.com/bids-standard/pybv/blob/4af6bbab86e6151a3a64d759d4eca4a15e9b253a/pybv/_export.py#L134) in  [_export.py](https://github.com/bids-standard/pybv/blob/4af6bbab86e6151a3a64d759d4eca4a15e9b253a/pybv/_export.py). 
I checked my raw file in MNE, and its annotations do indeed not contain an entry for `ch_names`. Did not dig deeper into the MNE code to find out what `ch_names` mean in the context of annotations (not directly obvious to me). 
Is that an issue with my files or could [_export.py](https://github.com/bids-standard/pybv/blob/4af6bbab86e6151a3a64d759d4eca4a15e9b253a/pybv/_export.py) check for the existence of the key first and skip it if not present (dunno if this will break things downstream)?

### PR DESCRIPTION
**Pull request by eioe**
closes #99 .

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
looks good to me, thanks!

Please:

1. add yourself to this file: https://github.com/bids-standard/pybv/blob/1a29f7413e6b8cffeb0caa6365443d0bd217735f/CITATION.cff#L32-L34
2. add an entry to the changelog, following the syntax you can see in previous entries: https://github.com/bids-standard/pybv/blob/main/docs/changelog.rst

**Comment by eioe** [comment]
thx. Pls check my comment in the issue, before you merge. So we make sure, I did not introduce some new problems downstream.

**Comment by sappelhoff** [comment]
I forgot to mention that you also need to add yourself here:

https://github.com/bids-standard/pybv/blob/1a29f7413e6b8cffeb0caa6365443d0bd217735f/docs/changelog.rst?plain=1#L9-L27

**Review by sappelhoff — APPROVED** [review]
Thanks for your first contribution @eioe -- may there be many more!

**Pull request merged**
